spring.application.name=nova
server.port=8761

spring.datasource.url=jdbc:postgresql://localhost:5432/nova_db
spring.datasource.username=postgres
spring.datasource.password=sql@22
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

